### ISSUE TITLE
log4j vulnerability in JBoss plugin

### ISSUE THREAD

**Issue by osmanburucu-ibm** [UrbanCode/IBM-UCD-PLUGINS#13]
Describe the bug
JBoss Application Server UCD Plugin v23 still has log4j jar 1.2.16. Since log4j 1.x is no longer supported it is coming as a vulnerability in Nessus security scan.

To Reproduce
Check for version in log4j.jar.

Expected behavior
It should be at least upgraded to use log4j v2.17.1

https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/issues/53

**Comment by osmanburucu** [comment]
Fixed with Version 24
